### ISSUE TITLE
run.py causing bugs when using uti.image_formater

### ISSUE THREAD

**Issue by Hong-Xiang** [Hong-Xiang/XLearning#2]
Traceback (most recent call last):                                                                                                           
  File "/home/hongxwing/Workspace/xlearn/run/run.py", line 199, in <module>                                                                  
    tf.app.run()                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run                                           
    sys.exit(main(sys.argv))                                                                                                                 
  File "/home/hongxwing/Workspace/xlearn/run/run.py", line 193, in main                                                                      
    infer_SR_Sino(argv)                                                                                                                      
  File "/home/hongxwing/Workspace/xlearn/run/run.py", line 103, in infer_SR_Sino                                                             
    image_orginal = uti.image_formater(image_orginal)                                                                                        
  File "/home/hongxwing/Workspace/xlearn/utils/image.py", line 212, in image_formater                                                        
    image = tensor2image(tensor, offset=offset)                                                                                              
  File "/home/hongxwing/Workspace/xlearn/utils/image.py", line 165, in tensor2image                                                          
    image_list, new_shape, strides=strides, margin0=margin0, margin1=margin1)                                                                
  File "/home/hongxwing/Workspace/xlearn/utils/tensor.py", line 243, in combine_tensor_list                                                  
    if not isinstance(tensor_list[0], np.ndarray):                                                                                           
IndexError: list index out of range

**Comment by Hong-Xiang** [comment]
Close for not using run.py.
